apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb
  namespace: db-ns
spec:
  containers:
  - name: mongodb-container
    image: mongo:latest
    ports:
    - containerPort: 27017

