apiVersion: v1
kind: Pod
metadata:
  name: javawebapp
  labels:
    app: javawebapp
    env: prod
  namespace: prod
spec:
  containers:
  - name: javawebapp
    image: kkeducationb2/java-webapp:1.1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: javawebappsvc
 namespace: prod
spec:
  type: ClusterIP
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
