apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    app: tomcat
  namespace: app-ns
spec:
  containers:
  - name: tomcat-container
    image: tomcat:9.0
    ports:
    - containerPort: 8080

